### ISSUE TITLE
Change sidenav icons

### ISSUE THREAD

**Issue by AmerAnsari** [AmerAnsari/kharjomarj#16]
Should use angular material icons

**Comment by mehdirajani5** [comment]
Hey! @AmerAnsari 
I can see sidebar, Can you please guide me where is a sidebar.

**Comment by AmerAnsari** [comment]
> Hey! @AmerAnsari
> I can see sidebar, Can you please guide me where is a sidebar.

The code?

**Comment by AmerAnsari** [comment]
Done #12
